before_script:
  - docker info

stages:
  - build
  - run

build_image:
  stage: build
  script:
    - ./code/my-demo-app/docker_build.sh || docker build -t 3jmaster/addo-demo-app ./code/my-demo-app/

run_with_vault:
  stage: run
  script:
    - echo "$VAULT_USERNAME"
    - echo "$CI_JOB_ID"
    - echo "$CI_PROJECT_DIR"
    - ./code/my-demo-app/docker_run.sh || docker run --network=isolated_nw --name 3jmaster-addo-demo-app 3jmaster/addo-demo-app
